"""Encode the mod's generated artwork as native 128x128 PlayStation textures.

Run manually after changing assets/mods/boss-roster/*.png; requires Pillow.
The committed header lets ordinary game builds avoid an image-tool dependency.
"""
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[1]
lines = ['/* Generated by tools/build_boss_portraits.py; mod artwork, not disc data. */',
         '#pragma once', '#include <stdint.h>', '']
for name in ('gaia', 'sho'):
    source = root / 'assets/mods/boss-roster' / (name + '.png')
    image = Image.open(source).convert('RGB').resize((128, 128), Image.Resampling.LANCZOS)
    pixels = []
    for r, g, b in image.getdata():
        word = (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)
        pixels.append(word or 0x8000)  # Opaque black in a non-blended FT4.
    lines.append(f'static const uint16_t toshinden_{name}_portrait[16384] = {{')
    for i in range(0, len(pixels), 16):
        lines.append('    ' + ', '.join(f'0x{v:04X}' for v in pixels[i:i + 16]) + ',')
    lines.extend(['};', ''])
(root / 'src/mods/toshinden_boss_portraits.h').write_bytes('\n'.join(lines).encode('utf-8'))
